#! /bin/bash

# Directories to create
dirs=('storage/private_uploads'
      'uploads/accessories'
      'uploads/avatars'
      'uploads/barcodes'
      'uploads/categories'
      'uploads/components'
      'uploads/companies'
      'uploads/consumables'
      'uploads/departments'
      'uploads/locations'
      'uploads/manufacturers'
      'uploads/models'
      'uploads/suppliers'
      'storage/dumps'
      'storage/keys'
      'storage/logs'
      'storage/framework/views'
      'storage/framework/sessions'
      'storage/framework/cache'
      'storage/debugbar'
      'storage/app/backups')

# Create directories on mounted storage
for dir in ${dirs[@]} ; do
  if [ ! -d "/config/$dir" ]; then
    mkdir -p "/config/$dir"
  fi
done

# Create API key if needed
if [ ! -f "/config/SNIPE_IT_APP_KEY.txt" ]
then
  echo "Generating SnipeIT app key for first run"
  key=$(php /var/www/html/artisan key:generate --show)
  echo $key > /config/SNIPE_IT_APP_KEY.txt
  echo "App Key set to $key you can modify the file to update /config/SNIPE_IT_APP_KEY.txt"
fi

# Ownership
chown -R abc:abc /config/

# If the Oauth DB files are not present copy the vendor files over to the db migrations
if [ ! -f "/var/www/html/database/migrations/*create_oauth*" ]; then
  cp -ax /var/www/html/vendor/laravel/passport/database/migrations/* /var/www/html/database/migrations/
fi
