#!/bin/sh

# create data directories
for dir in \
  'data/private_uploads' \
  'data/uploads' \
  'data/uploads/accessories' \
  'data/uploads/avatars' \
  'data/uploads/barcodes' \
  'data/uploads/categories' \
  'data/uploads/components' \
  'data/uploads/companies' \
  'data/uploads/consumables' \
  'data/uploads/departments' \
  'data/uploads/locations' \
  'data/uploads/manufacturers' \
  'data/uploads/models' \
  'data/uploads/suppliers' \
  'dumps' \
  'keys' \
  'logs' \
  'framework/views' \
  'framework/sessions' \
  'framework/cache' \
  'debugbar' ; do
	  mkdir -p "/config/$dir"
done

# Create API key if needed
if [ ! -f "/config/SNIPE_IT_APP_KEY.txt" ]
then
  echo "Generating SnipeIT app key for first run"
  key=$(php /var/www/html/artisan key:generate --show)
  echo $key > /config/SNIPE_IT_APP_KEY.txt
  echo "App Key set to $key you can modify the file to update /config/SNIPE_IT_APP_KEY.txt"
fi

# Ownership
chown -R abc:abc /config/ /var/www/html/storage/

# If the Oauth DB files are not present copy the vendor files over to the db migrations
if [ ! -f "/var/www/html/database/migrations/*create_oauth*" ]; then
  cp -ax /var/www/html/vendor/laravel/passport/database/migrations/* /var/www/html/database/migrations/
fi
